# apiVersion: autoscaling/v2
# kind: HorizontalPodAutoscaler
# metadata:
#   name: rs-deployment
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: rs-deployment
#   minReplicas: 1
#   maxReplicas: 5
#   metrics:
#   - type: Resource
#     resource:
#       name: cpu
#       target:
#         type: Utilization
#         targetAverageUtilization: 70
#   - type: Resource
#     resource:
#       name: memory
#       target:
#       type: Utilization
#         targetAverageUtilization: 70

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: rs-deployment
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rs-deployment
  minReplicas: 3 # store the min, max replicas some where else
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70 
      



  